[package]
name = "fcm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
tiny_http = "0.12"
ureq = { version = "2", features = ["json"] }
libc = "0.2"
dirs = "5"
